name: rikulo_ui
version: 0.7.0+2
description: > 
  A cross-platform framework for creating amazing 
  Web and native mobile applications in Dart & HTML5.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org/projects/ui
documentation: http://docs.rikulo.org/ui
dependencies:
  rikulo_commons: any
  browser: any
  meta: any
